---
- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
    - name: update all packages 
      apt:
       name: "*"
       state: latest
       update_cache: yes
    - name: Get the GPG key of the repository
      shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
      tags: setup
    - name: Change the permission of gpg
      shell: "sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
      tags: setup
    - name: Apply the repository
      shell: 'echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /" >/etc/apt/sources.list.d/kubernetes.list'
      tags: setup
    - name: Install CRI
      shell: "curl -s -fsSL https://get.docker.com | sh"
      tags: setup
    - name: Install k8s pkg
      apt:
        pkg:
          - kubelet 
          - kubeadm 
          - kubectl 
          - kubernetes-cni
        state: present
        update_cache: yes
      tags: setup
    - name: Hold the k8s pkgs
      shell: "apt-mark hold kubelet kubeadm kubectl"
      tags: setup
    - name: update containerd configs
      shell: mkdir -p /etc/containerd ; containerd config default | sudo tee /etc/containerd/config.toml; sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      tags: setup
    - name: restart containerd service
      service:
        name: containerd
        state: restarted
      tags: setup
- hosts: master
  gather_facts: false
  remote_user: root
  tasks:
    - name: Init the k8s cluster
      shell: "kubeadm init --apiserver-advertise-address=master-ip --pod-network-cidr=172.16.0.0/16"
      tags: k8sboot
    - name: get the token for join
      command: "kubeadm token create --print-join-command"
      changed_when: false
      register: join_cmd
      tags: k8sboot
    - name: Set fact for join command
      set_fact:
        join_command: "{{ join_cmd.stdout }}"
      delegate_to: localhost
      run_once: true
      tags: k8sboot

- hosts: worker
  gather_facts: false
  remote_user: root
  tasks:
    - name: Join the node to the Kubernetes cluster
      ansible.builtin.shell: "{{ hostvars[groups['master'][0]]['join_command'] }}"
      tags: k8sboot

- hosts: localhost
  tasks:
    - name: create .kube dirctory
      file:
        path: ./.kube
        state: directory
      tags: k8sboot

- hosts: master
  gather_facts: false
  remote_user: root
  tasks:
    - name: Fetch kubeconfig file from master to localhost
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./.kube/config
        flat: yes
      run_once: true
      tags: k8sboot

- name: Deploy Calico CNI plugin
  hosts: localhost
  environment:
    K8S_AUTH_KUBECONFIG: ./.kube/config
  tasks:
    - name: Apply Calico manifest to the cluster
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/calico.yaml
      tags: k8sboot
    - name: wait for calico pod become available
      ansible.builtin.wait_for:
        timeout: 360
      delegate_to: localhost
      tags: k8sboot
    - name: Apply Metrics server 
      kubernetes.core.k8s:
        state: present
        src: ./metrics-server.yaml
      tags: k8sboot
    - name: Clone the rook ceph repo
      ansible.builtin.git:
        repo: https://github.com/rook/rook.git
        dest: /opt/ceph/rook
        version: release-1.17
      tags: ceph
    - name: deploy CEPH CRDs
      kubernetes.core.k8s:
        state: present 
        src: ./rook/deploy/examples/crds.yaml
      tags: ceph
    - name: deploy ceph common yamls
      kubernetes.core.k8s:
        state: present
        src: ./rook/deploy/examples/common.yaml
      tags: ceph
    - name: deploy CEPH operator
      kubernetes.core.k8s:
        state: present
        namespace: rook-ceph
        src: ./rook/deploy/examples/operator.yaml
      tags: ceph
    - name: wait for operator pod become available 
      ansible.builtin.wait_for:
        timeout: 240
      delegate_to: localhost
      tags: ceph
    - name: deploy ceph 
      kubernetes.core.k8s:
        state: present
        namespace: rook-ceph
        src: ./rook/deploy/examples/cluster.yaml
      tags: ceph
    - name: wait for CEPH become available
      ansible.builtin.wait_for:
        timeout: 900
      delegate_to: localhost
      tags: ceph
    - name: deploy ceph toolbox
      kubernetes.core.k8s:
        state: present
        namespace: rook-ceph
        src: ./rook/deploy/examples/toolbox.yaml
      tags: ceph
    - name: deploy ceph rbd storage class
      kubernetes.core.k8s:
        state: present
        namespace: rook-ceph
        src: ./rook/deploy/examples/csi/rbd/storageclass.yaml
      tags: cephrbdsc
